# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: hephaestos
description: A fork of Bazzite with the COSMIC desktop environment 

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome-nvidia-open
image-version: latest

modules:
  # The 'files' module is separate from the package manager
  - type: files
    files:
      - source: system
        destination: /

  # Standardized DNF / rpm-ostree module for packages
  - type: rpm-ostree
    repos:
      # Wrapped in quotes to ensure YAML parses them as strings
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ryanabx/cosmic-epoch/repo/fedora-%OS_VERSION%/ryanabx-cosmic-epoch-fedora-%OS_VERSION%.repo
    install:
      - micro
      - starship
      - cosmic-desktop
      - cosmic-greeter
      - kde-connect
  # Systemd module properly separated and un-indented
  - type: systemd
    system:
      enabled:
        - cosmic-greeter.service
      disabled:
        - gdm.service
    user: 
      enabled:
        - kdeconnect.service
